[project]
name = "work"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "hdbscan>=0.8.40",
    "opencv-python>=4.11.0.86",
    "scikit-learn>=1.7.0",
    "ultralytics>=8.3.156",
]
